cemi/cemi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

cemi/store/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('shop/', views.shop, name='shop'),
    path('base/', views.base, name='base'),
    path('details/<int:item_id>/', views.details, name='details'),
    path('cart/', views.cart, name="cart"),
    path('add_to_cart/<int:item_id>', views.add_to_cart, name='add_to_cart'),
    path('user_register/', views.user_register, name='user_register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
     path('user_profile/', views.user_profile, name='user_profile'),
    path('reduce_item_quantity/<int:item_id>', views.reduce_item_quantity, name='reduce_item_quantity'),
    path('checkout/', views.checkout, name='checkout'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('success/', views.success, name='success'),
    path('order/' , views.order, name='order'),
    path('orders/', views.orders, name='orders'),
    path('handling_404/', views.handling_404, name='handling_404'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
     path('category/<str:category>/', views.shop_category, name='shop_category'),




]

cemi/store/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(null=True)
    phone_number = models.CharField(max_length=20, null=True)
    address = models.TextField(null=True)

    # Add other fields as needed

    def __str__(self):
        return self.user.username 
    
    
# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    email = models.EmailField()
    website = models.URLField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
# models.py

class items(models.Model):
    STATUS_CHOICES = [
        ('off 20%', 'off 20%'),
        ('off 50%', 'off 50%'),
        ('off 30%', 'off 30%'),
    ]
    CATEGORY_CHOICES = [
        ('televisions', 'Televisions'),
        ('phones', 'Phones'),
        ('shoes', 'Shoes'),
        ('cutleries', 'Cutleries'),
        ('electrical_appliances', 'Electrical Appliances'),
        ('clothes', 'Clothes'),
        ('accessories', 'Accessories'),
        ('housewares', 'Housewares'),
        # Add more categories as needed
    ]
    
 
    category = models.CharField(null=True, max_length=50, choices=CATEGORY_CHOICES)
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=100, null=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    store = models.ForeignKey('Store', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    percentage_discount = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    images = models.ImageField(null=True, upload_to='static/', default='fridge.jpg')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='available')

    def __str__(self):
        return self.name

    def sold(self):
        return self.status.capitalize()


class cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(items, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{self.user} - {self.item} - {self.quantity}"
    
    

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    delivery_address = models.TextField()
    items = models.TextField()  # You can use JSONField if you want to store the items as structured data
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Order {self.id} by {self.user}'


# models.py

from django.db import models
from django.contrib.auth.models import User
from .models import items

class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    item = models.ForeignKey(items, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.IntegerField(choices=RATING_CHOICES)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Review for {self.item.name} by {self.user.username}"



# models.py
from django.db import models

cemi/store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Store, items, Profile, Review
from .cart import Cart
from django.contrib import messages
from django.http import JsonResponse
from .forms import RegisterForm, LoginForm, LogoutForm, UserProfileForm, ReviewForm
from decimal import Decimal
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from .forms import OrderForm
from .models import Order
from .cart import Cart  # Import your Cart class
from django.contrib.auth.decorators import login_required


def custom_login_required(view_func):
    def wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, 'Please login to your account or register to view this part of the site.')
            return redirect('user_login')  # Ensure this URL name matches your login view URL name
        return view_func(request, *args, **kwargs)
    return wrapped_view

def activateEmail(request, user, to_email):
    messages.success(request, f'You have successfully registered. \n Please check your email {to_email} to activate your account.')

# views.py



from django.contrib.auth import login
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .utils import activateEmail  # Ensure this import is correct

def user_register(request):
    form = RegisterForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            user = User.objects.create_user(username=username, password=password, email=email)
            user.is_active = False  # User is not active until they confirm their email
            user.save()
            
            activateEmail(request, user, email)
            messages.success(request, f'You have successfully registered. \n Your account activation link has been sent to  {email}. please check your email for account activation.')
            return redirect('shop')
    return render(request, 'register.html', {'form': form})





def user_login(request):
    form = LoginForm(request.POST)
    if request.method == 'POST':
        username = form.data['username']
        password = form.data['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect('shop')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'login.html', {'form': form})

@custom_login_required
def user_logout(request):
    form = LogoutForm(request.POST)
    if request.method == 'POST':
        logout(request)
        messages.success(request, 'You have logged out. Welcome back to cemi shop')
        return redirect('user_login')
    return render(request, 'logout.html', {'form': form})


@custom_login_required
def home(request):
    if 'q' in request.GET:
        q = request.GET['q']
        items_page = items.objects.filter(name__icontains=q)
    else:
        items_page = items.objects.all()
    user_page = Profile.objects.all()
    store_page = Store.objects.all()
    cart = Cart(request)
    total_quantity = sum(item['quantity'] for item in cart.cart.values())

    context = {
        'user_page': user_page,
        'store_page': store_page,
        'items_page': items_page,
        'total_quantity': total_quantity,
        'cart': cart,

    }
    return render(request, 'home.html', context)






def base(request):
    if 'q' in request.GET:
        q = request.GET['q']
        items_page = items.objects.filter(name__icontains=q)
    else:
        items_page = items.objects.all()
    cart = Cart(request)
    total_quantity = sum(item['quantity'] for item in cart.cart.values())
    user_page = Profile.objects.all()
    store_page = Store.objects.all()

    context = {
        'user_page': user_page,
        'store_page': store_page,
        'items_page': items_page,
        'total_quantity': total_quantity,
        'cart': cart,
    }
    return render(request, 'base.html', context)

# views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import items, Review
from .forms import ReviewForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def details(request, item_id):
    item = get_object_or_404(items, pk=item_id)
    user_page = Profile.objects.all()
    store_page = Store.objects.all()
    items_page = items.objects.all()
    cart = Cart(request)
    total_quantity = sum(item['quantity'] for item in cart.cart.values())

    # Fetch reviews for the specific item
    reviews = Review.objects.filter(item=item)

    # Handle review form submission
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.item = item
            review.user = request.user
            review.save()
            messages.success(request, 'Your review has been submitted successfully.')
            return redirect('details', item_id=item_id)
        else:
            messages.error(request, 'Failed to submit review. Please check the form data.')
    else:
        form = ReviewForm()

    context = {
        'user_page': user_page,
        'store_page': store_page,
        'items_page': items_page,
        'item': item,
        'reviews': reviews,  # Pass the reviews to the template
        'total_quantity': total_quantity,
        'cart': cart,
        'form': form,  # Pass the review form to the template
    }

    return render(request, 'details.html', context)



@custom_login_required
def cart(request):
    cart = Cart(request)
    total_quantity = sum(item['quantity'] for item in cart.cart.values())

    # Fetch the item objects including images
    items_with_prices = []
    total_price = 0  # Initialize total price

    for item_id, item_info in cart.cart.items():
        item = get_object_or_404(items, id=item_id)
        item.quantity = item_info['quantity']  # Add quantity to the item object
        total_item_price = item.price * item_info['quantity']
        total_price += total_item_price  # Add item's total price to the total price
        items_with_prices.append((item, total_item_price))  # Append tuple of item and total price

    context = {
        'cart': cart,
        'total_quantity': total_quantity,
        'items_with_prices': items_with_prices,  # Pass the items with total prices to the template
        'total_price': total_price,  # Pass total price to the template
    }
    return render(request, 'cart.html', context)


@custom_login_required
def reduce_item_quantity(request, item_id):
    cart = Cart(request)
    cart.reduce_quantity(item_id)
    return redirect('cart')

@custom_login_required
def checkout(request):
    cart = Cart(request)
    total_quantity = sum(item['quantity'] for item in cart.cart.values())

    # Fetch the item objects including images
    items_with_prices = []
    total_price = 0  # Initialize total price

    for item_id, item_info in cart.cart.items():
        item = get_object_or_404(items, id=item_id)
        item.quantity = item_info['quantity']  # Add quantity to the item object
        total_item_price = item.price * item_info['quantity']
        total_price += total_item_price  # Add item's total price to the total price
        items_with_prices.append((item, total_item_price))  # Append tuple of item and total price
    context = {
        'cart': cart,
        'total_quantity': total_quantity,
        'items_with_prices': items_with_prices,  # Pass the items with total prices to the template
        'total_price': total_price,  # Pass total price to the template
    }
    return render(request, 'checkout.html', context)

@custom_login_required
def add_to_cart(request, item_id):
    item = get_object_or_404(items, id=item_id)
    cart = Cart(request)
    cart.add(item)
    total_price = Decimal(item.price) * cart.cart[str(item_id)]['quantity']
    return redirect('cart')

@custom_login_required
def user_profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    latest_order = Order.objects.filter(user=request.user).order_by('-created_at').first()
    cart = Cart(request)
    total_quantity = sum(item['quantity'] for item in cart.cart.values())
    context = {
        'profile': profile,
        'latest_order': latest_order,
        'total_quantity': total_quantity,
        'cart': cart,


    }

    return render(request, 'profile.html', context)


def shop(request):
    if 'q' in request.GET:
        q = request.GET['q']
        items_page = items.objects.filter(name__icontains=q)
    else:
        items_page = items.objects.all()
    cart = Cart(request)
    user_page = Profile.objects.all()
    store_page = Store.objects.all()
    total_quantity = sum(item['quantity'] for item in cart.cart.values())
    context = {
        'user_page': user_page,
        'store_page': store_page,
        'items_page': items_page,
        'cart': cart,
        'total_quantity': total_quantity,


    }
    return render(request, 'shop.html', context)


@custom_login_required
def about(request):
    cart = Cart(request)
    context = {
        'cart': cart,
        }
    return render(request, 'about.html', context)

def success(request):
    return render(request, 'success.html')

def welcome(request):
    user_page = Profile.objects.all()

cemi/store/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About Us{% endblock %}
{% block heading %}About Cemi Shop{% endblock %}
{% block content %}
<style>
    .about-container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        font-family: Arial, sans-serif;
        line-height: 1.6;
    }

    .about-container h1, .about-container h2 {
        color: blue;
    }

    .about-container p {
        margin-bottom: 20px;
    }

    .contact-list {
        list-style-type: none;
        padding: 0;
    }
    button.navbar-toggler {
        background-color: #eb9e42;
    }

    .contact-list li {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .contact-list li a {
        color: #2c3e50;
        text-decoration: none;
        display: flex;
        align-items: center;
    }

    .contact-list li a img {
        width: 30px;
        height: 30px;
        margin-right: 10px;
        border-radius: 50%;
        transition: transform 0.3s ease;
    }

    .contact-list li a:hover img {
        transform: scale(1.2);
    }

    .contact-list li a:hover {
        text-decoration: underline;
    }

    .hero {
        text-align: center;
        padding: 50px 0;
        background-color: #f4f4f4;
        border-radius: 10px;
        margin-bottom: 20px;
    }

    .hero h2 {
        margin-bottom: 20px;
    }

    .btn {
        display: inline-block;
        background-color: #333;
        color: #fff;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
    }

    .products {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-evenly;
    }

    .product {
        margin-bottom: 20px;
        text-align: center;
        flex: 1;
    }

    .product img {
        max-width: 100%;
        border-radius: 10px;
    }
</style>

<div class="container about-container">
    <p>Cemi Shop is an innovative online selling platform designed to provide users with a seamless shopping experience. As an e-commerce destination, Cemi Shop offers a wide range of products spanning various categories, catering to the diverse needs and preferences of its customers.</p>

    <p>One of the standout features of Cemi Shop is its commitment to customer satisfaction. With a user-centric approach, Cemi Shop ensures that every step of the shopping journey is convenient and rewarding. To enhance the shopping experience, Cemi Shop offers free shipping on all purchases, allowing customers to enjoy their favorite products without worrying about additional costs.</p>

    <p>Furthermore, Cemi Shop takes pride in the quality of its products and the trust it builds with its customers. Understanding that sometimes products may not meet expectations or may arrive damaged, Cemi Shop offers a hassle-free return policy. Customers can easily return products that do not meet their satisfaction, ensuring that they always receive the best value for their money.</p>

    <p>In essence, Cemi Shop is not just an online marketplace; it's a reliable partner in helping customers discover and purchase products they love, with the assurance of excellent service, free shipping, and hassle-free returns. With Cemi Shop, shopping becomes more than just a transaction; it becomes an enjoyable and fulfilling experience.</p>

    <div class="hero">
        <h2>Meet the Developers</h2>
        <p>Get to know the brilliant minds behind Cemi Shop. Connect with Milugo Geofrey and Celestine Kibor on their professional profiles.</p>
        <div class="row">
            <div class="col-md-6">
                <h2>Milugo Geofrey Ouma</h2>
                <p>AI engineering student at Maseno University</p>
                <img src="{% static 'geofrey.jpeg' %}" alt="Milugo Geofrey" class="img-fluid" style="border-radius: 10px;">
            </div>
            <div class="col-md-6">
                <h2>Celestine Kibor</h2>
                <p>Computer Science student at Maseno University</p>
                <img src="{% static 'celee.jpg' %}" alt="Celestine Kibor" class="img-fluid" style="border-radius: 10px;">
            </div>
        </div>
    </div>

    <h2>Contact Us</h2>
    <ul class="contact-list">
        <li><a href="https://www.linkedin.com/in/geofrey-milugo-msu27345/"><img src="{% static 'linkedin.jpg' %}" alt="LinkedIn"> LinkedIn: Milugo Geofrey</a></li>
        <li><a href="https://www.linkedin.com/in/celetine-kibor?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADvVq7QByoueIe-yMQgo1gUYZYiS68Xb1lo&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3BNo%2FYrTKKSHuTICcwqdEDjA%3D%3D"><img src="{% static 'linkedin.jpg' %}" alt="LinkedIn"> LinkedIn: Celestine Kibor</a></li>
        <li><a href="https://twitter.com/milugo_g"><img src="{% static 'twitter.jpg' %}" alt="Twitter"> X: @milugogeofrey</a></li>
        <li><a href="https://twitter.com/@Celestine_celee"><img src="{% static 'twitter.jpg' %}" alt="Twitter"> X: @Celestine_celee</a></li>
        <li><a href="https://github.com/pha12thom"><img src="{% static 'github.PNG' %}" alt="GitHub"> GitHub: Milugo Geofrey</a></li>
        <li><a href="https://github.com/Celeekeybor"><img src="{% static 'github.PNG' %}" alt="GitHub"> GitHub: Celeekeybor</a></li>
    </ul>
</div>
{% endblock %}

cemi/store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
   
   
</head>
<body>
    <!-- Loader -->
    <div id="loader">
        <img src="{% static 'cart.png' %}" alt="Loading..." width="100px">
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <!-- Header -->
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'cemi.png' %}" alt="Cemi Store Logo" width="70px">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop' %}">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'orders' %}">My orders</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'televisions' %}">Televisions</a></li>
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'shoes' %}">Shoes</a></li>
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'cutleries' %}">Cutleries</a></li>
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'electrical_appliances' %}">Electronics</a></li>
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'clothes' %}">clothes</a></li>
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'accessories' %}">Accessories</a></li>
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'phones' %}">phones</a></li>
                                <li><a class="dropdown-item" href="{% url 'shop_category' 'housewares' %}">Housewares</a></li>
                               
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about' %}">About Us</a>
                        </li>
                    </ul>
                    <form class="d-flex" action="{% url 'shop' %}" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cart' %}"> <img src="{% static 'cart.png' %}" alt="cart" width="30px">
                                <i class="fas fa-shopping-cart"><span class="badge bg-danger">{{ total_quantity }}</span></i>
                              
                            </a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user_profile' %}" style="background-color:#e67e22; border-radius: 30px;">
                                    {{ request.user.username }}
                                    <i class="fas fa-chevron-down"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user_login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user_register' %}">Sign Up</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Content Block -->
    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>About Us</h5>
                    <p>Welcome to Cemi Online Store, your one-stop destination for all your home equipment needs. We provide high-quality products with exceptional customer service.</p>
                </div>
                <div class="col-md-2">
                    <h5>Quick Links</h5>
                    <ul class="list-unstyled footer-links">
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'shop' %}">Shop</a></li>
                        <li><a href="{% url 'orders' %}">My Orders</a></li>
                        <li><a href="{% url 'about' %}">About Us</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Contact Us</h5>
                    <p>Email: geofreymilugo@gmail.com</p>
                    <p>Phone: +254112155880</p>
                    <div class="social-icons">
                        <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.twitter.com/milugo_g" target="_blank"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.instagram.com/milugo_g" target="_blank"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <h5>Newsletter</h5>
                    <form class="subscribe-form">
                        <input type="email" placeholder="Enter your email">
                        <button type="submit">Subscribe</button>
                    </form>
                </div>
            </div>
            <hr>
            <div class="text-center">
                <p>&copy; {% now "Y" %} Cemi Store. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <script>
        // Sidebar toggle function
        function toggleSidebar() {
            document.querySelector('.sidebar').classList.toggle('active');
        }

        // Hide loader after page load
        window.addEventListener('load', function() {
            document.getElementById('loader').style.display = 'none';
        });
    </script>
</body>
</html>

cemi/store/templates/order.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock %}
{% block heading %}Checkout Payment{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Enter your details to complete the purchase</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email:</label>
                            {{ form.email }}
                        </div>
                        <div class="mb-3">
                            <label for="id_phone_number" class="form-label">Phone Number:</label>
                            {{ form.phone_number }}
                        </div>
                        <div class="mb-3">
                            <label for="id_delivery_address" class="form-label">Delivery Address:</label>
                            {{ form.delivery_address }}
                        </div>
                        <div class="text-center">
                            <p class="h5">Total Price: <strong>ksh {{ total_price }}</strong></p>
                            <button type="submit" class="btn btn-primary">Submit Order</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}